using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEditor.Build;
using UnityEditor.Build.Reporting;
using UnityEngine;

namespace K10.Optimization.Editor
{
    // Bakes the (editor-only) Project Settings values into a compiled runtime source file so player
    // builds get the tiers without any ScriptableObject. The generated class self-registers via
    // [RuntimeInitializeOnLoadMethod] and calls the existing HardwareTier.SetMemoryTiers.
    public static class HardwareTierBakedCodeGenerator
    {
        // Lives in the default assembly (Assembly-CSharp), which auto-references K10, so it can reach
        // HardwareTier. Kept outside the K10 lib folder because it holds project-specific values.
        const string GeneratedPath = "Assets/Generated/K10/HardwareTierBaked.generated.cs";
        const string MenuPath = "Tools/K10/Optimization/Regenerate Hardware Tier Baked Settings";

        [MenuItem (MenuPath)]
        public static void RegenerateMenu () => Regenerate ();

        // Writes the generated file if its contents changed. Returns true when the file was (re)written.
        public static bool Regenerate ()
        {
            string source = BuildSource (HardwareTierProjectSettings.instance);

            string directory = Path.GetDirectoryName (GeneratedPath);
            if (!Directory.Exists (directory)) Directory.CreateDirectory (directory);

            string existing = File.Exists (GeneratedPath) ? File.ReadAllText (GeneratedPath) : null;
            if (existing == source) return false;

            File.WriteAllText (GeneratedPath, source);
            AssetDatabase.ImportAsset (GeneratedPath);
            return true;
        }

        static string BuildSource (HardwareTierProjectSettings settings)
        {
            StringBuilder sb = new StringBuilder ();
            sb.Append ("// <auto-generated>\n");
            sb.Append ("// Baked from Project Settings > K10 > Hardware Tier (ProjectSettings/HardwareTier.asset).\n");
            sb.Append ("// Do NOT edit by hand. Regenerate from that settings page or the '" + MenuPath + "' menu.\n");
            sb.Append ("// </auto-generated>\n");
            sb.Append ("using UnityEngine;\n\n");
            sb.Append ("internal static class HardwareTierBaked\n");
            sb.Append ("{\n");
            sb.Append ("    [RuntimeInitializeOnLoadMethod (RuntimeInitializeLoadType.AfterAssembliesLoaded)]\n");
            sb.Append ("    static void Apply ()\n");
            sb.Append ("    {\n");

            // Per-platform overrides first (deduped so we never emit duplicate switch labels),
            // then the default as the fallback.
            List<HardwareTierProjectSettings.PlatformOverride> overrides = settings.PlatformOverrides;
            HashSet<RuntimePlatform> emitted = new HashSet<RuntimePlatform> ();
            bool switchOpen = false;

            if (overrides != null)
            {
                foreach (HardwareTierProjectSettings.PlatformOverride entry in overrides)
                {
                    if (entry == null || !emitted.Add (entry.platform)) continue;

                    if (!switchOpen)
                    {
                        sb.Append ("        switch (Application.platform)\n");
                        sb.Append ("        {\n");
                        switchOpen = true;
                    }

                    sb.Append ($"            case RuntimePlatform.{entry.platform}: {ToCall (entry.memoryTiers?.ToArray ())} return;\n");
                }
            }

            if (switchOpen) sb.Append ("        }\n");

            sb.Append ("        " + ToCall (settings.DefaultMemoryTiers) + "\n");
            sb.Append ("    }\n");
            sb.Append ("}\n");
            return sb.ToString ();
        }

        static string ToCall (int[] tiers)
        {
            int low = tiers != null && tiers.Length > 0 ? tiers[0] : 0;
            int mid = tiers != null && tiers.Length > 1 ? tiers[1] : 0;
            int high = tiers != null && tiers.Length > 2 ? tiers[2] : 0;
            return $"HardwareTier.SetMemoryTiers ({low}, {mid}, {high});";
        }
    }

    // Safety net: make sure the committed generated file matches the current settings before a build.
    // Regeneration cannot recompile for the in-flight build, so fail once and let the user rebuild.
    class HardwareTierBakeBuildPreprocessor : IPreprocessBuildWithReport
    {
        public int callbackOrder => 0;

        public void OnPreprocessBuild (BuildReport report)
        {
            if (HardwareTierBakedCodeGenerator.Regenerate ())
                throw new BuildFailedException (
                    "Hardware Tier baked settings were out of date and have been regenerated. Please build again.");
        }
    }
}
